server.port=8080
spring.data.mongodb.uri=mongodb://localhost:27017/bigdata
spring.data.mongodb.database=bigdata
spring.application.name=BigdAtaProject1
spring.main.allow-bean-definition-overriding=true
